version: '3'
services:
  db:
    image: postgres:9.6
  rails:
    image: ruby:2.4.2
    # environment:
    #   DATABASE_URL: postgres://postgres:@db:5432/db
    environment:
      - DATABASE_URL=postgres://postgres:@db:5432/db
    volumes:
      - ./:/app
      - ./docker/log:/app/log
      - ./docker/vendor-bundle:/app/vendor/bundle
    depends_on:
      - db
    working_dir: /app
    command: |-
      /bin/bash -c \
      "sleep 1
      bundle install --path vendor/bundle --without development production
      RAILS_ENV=test bin/rails db:setup
      RAILS_ENV=test bin/rake"
      # sleep 1 を挟まないとDBへの接続が失敗する(sleep 0に変えてみるといいです)
