version: '3'
services:
  db:
    image: postgres:9.6
  rails:
    image: ruby:2.4.2
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/db
    volumes:
      - ./:/app
    depends_on:
      - db
    working_dir: /app
    command: |-
      /bin/bash -c \
      "sleep 1
      bundle install --path vendor/bundle --without development production
      RAILS_ENV=test bin/rake db:setup
      RAILS_ENV=test bin/rake"
      # sleep 1 を挟まないとDBへの接続が失敗する(sleep 0に変えてみるといいです)
